# -*- coding: utf-8 -*-
"""DAC_Phase4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XpaT5HHWulaXPSaWxmK8jJNMzGVLrULc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
product=pd.read_csv("statsfinal.csv")
product

mean = np.mean(product)
mean

std_dev = np.std(product)
std_dev

from matplotlib import pyplot as plt
x = mean
y = std_dev
plt.plot(mean,std_dev)
plt.title("Line graph")
plt.ylabel('Y axis')
plt.xlabel('X axis')
plt.show()

total_cases = product['S-P1'].sum()
total_deaths = product['S-P2'].sum()
labels = ['S-P1', 'S-P2']
sizes = [total_cases, total_deaths]
colors = ['indigo', 'red']
explode = (0.1, 0)
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=140)
plt.axis('equal')
plt.title('Revenue of P1 and P2')
plt.show()

plt.bar(mean, std_dev, color=['blue', 'red'])
plt.xlabel('mean')
plt.ylabel('std_dev')
plt.title('Mean and Standard Deviation')
plt.show()

correlation = product['S-P1'].corr(product['S-P2'])
print("Correlation between S-P1 and S-P2:", correlation)

product['S-P1_Variation'] = product['S-P1'].pct_change() * 100
product['S-P2_Variation'] = product['S-P2'].pct_change() * 100
print(product[['S-P1_Variation', 'S-P2_Variation']])